### ISSUE TITLE
typescript项目引入会报错提示，无法找到模块“vite-plugin-style-to-vw”的声明文件。

### ISSUE THREAD

**Issue by paker777** [cq112233/vite-plugin-style-to-vw#1]
### 提示：无法找到模块“vite-plugin-style-to-vw”的声明文件。“D:/项目/vue3-ts/node_modules/.pnpm/vite-plugin-style-to-vw@1.2.0/node_modules/vite-plugin-style-to-vw/dist/index.mjs”隐式拥有 "any" 类型。

![image](https://github.com/user-attachments/assets/21a19682-382e-4b85-9141-6d690f4018f2)

**Comment by cq112233** [comment]
> ### 提示：无法找到模块“vite-plugin-style-to-vw”的声明文件。“D:/项目/vue3-ts/node_modules/.pnpm/vite-plugin-style-to-vw@1.2.0/node_modules/vite-plugin-style-to-vw/dist/index.mjs”隐式拥有 "any" 类型。
> ![image](https://private-user-images.githubusercontent.com/85239013/351548632-21a19682-382e-4b85-9141-6d690f4018f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTIwNDIsIm5iZiI6MTcyMTgxMTc0MiwicGF0aCI6Ii84NTIzOTAxMy8zNTE1NDg2MzItMjFhMTk2ODItMzgyZS00Yjg1LTkxNDEtNmQ2OTBmNDAxOGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA5MDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMjRmZjAzMDY5NzE0OTI3MTUyMjg0ZWM1MjQ1YmZkZWMzOTZjYzBhMzNkZWZkZDMxZjI3MGJiZTk4OTNjMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jEGvakz1CeFF7glG7GFaoq_JWPwvxCZ4IdylnmBt1_Q)

已修复
