### ISSUE TITLE
大部分ui组件有很多内置属性可以输入px，但无法转换

### ISSUE THREAD

**Issue by paker777** [cq112233/vite-plugin-style-to-vw#2]
![image](https://github.com/user-attachments/assets/ff578752-c53e-482e-aaf3-fa181301ca8f)
![image](https://github.com/user-attachments/assets/5c5c03df-708c-4910-b1be-d43345c7f953)

**Comment by paker777** [comment]
[更改了正则表达式](https://github.com/cq112233/vite-plugin-style-to-vw/pull/3)
可以把标签内所有属性里带px单位的转换为vw😊

**Comment by cq112233** [comment]
> [更改了正则表达式](https://github.com/cq112233/vite-plugin-style-to-vw/pull/3) 可以把标签内所有属性里带px单位的转换为vw😊

这个插件设计初衷是只转style里面的px

因为有原子化插件如windicss  在class中写成 class='w-20px' 是不能转换的

你可以通过stylePxToVw自己手动转化  stylePxToVw里面的，虽然比较麻烦点

```javascrip

import { stylePxToVw } from "vite-plugin-style-to-vw";


<van-image :size="stylePxToVw('28px)">
```

你那种全部替换，到时我在加个配置选项🤔

**Comment by paker777** [comment]
> > [改变了正则表达式](https://github.com/cq112233/vite-plugin-style-to-vw/pull/3)可以把标签内所有属性里带px单位的转换为vw😊
> 
> 这个插件设计初衷​​只是在 px 中转风格
> 
> 因为有原子化插件如windicss在class中写成class='w-20px'是不能转换的
> 
> 你可以通过stylePxToVw自己手动转化stylePxToVw里面的，虽然比较麻烦点
> 
> ```
> 
> import { stylePxToVw } from "vite-plugin-style-to-vw";
> 
> 
> <van-image :size="stylePxToVw('28px)">
> ```
> 
> 你那时全部替换，到了我在加个配置选项的时候🤔

好的，希望可以手动配置需要转换的属性，这样对于不同的组件也能灵活处理，例如 `['width', 'height', 'size']`😁

**Comment by cq112233** [comment]
> > > [改变了正则表达式](https://github.com/cq112233/vite-plugin-style-to-vw/pull/3)可以把标签内所有属性里带px单位的转换为vw😊
> > 
> > 
> > 这个插件设计初衷​​只是在 px 中转风格
> > 因为有原子化插件如windicss在class中写成class='w-20px'是不能转换的
> > 你可以通过stylePxToVw自己手动转化stylePxToVw里面的，虽然比较麻烦点
> > ```
> > 
> > import { stylePxToVw } from "vite-plugin-style-to-vw";
> > 
> > 
> > <van-image :size="stylePxToVw('28px)">
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 你那时全部替换，到了我在加个配置选项的时候🤔
> 
> 好的，希望可以手动配置需要转换的属性，这样对于不同的组件也能灵活处理，例如 `['width', 'height', 'size']`😁

这vite vue模版编译后组件prop 接收到的是转换后的 ，但react，模版是处理成功了，但编译后组件props接收到的还是原来的没转换的🤔

**Comment by paker777** [comment]
> > > > [改变了正则表达式](https://github.com/cq112233/vite-plugin-style-to-vw/pull/3)可以把标签内所有属性里带px单位的转换为vw😊
> > > 
> > > 
> > > 插件这个设计初中​​只是在px中转风格
> > > 因为有原子化通过插件如windicss在class中写成class='w-20px'是不能转换的
> > > 你可以stylePxToVw自己手动转化stylePxToVw里面的，虽然比较麻烦点
> > > ```
> > > 
> > > import { stylePxToVw } from "vite-plugin-style-to-vw";
> > > 
> > > 
> > > <van-image :size="stylePxToVw('28px)">
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 你随后全部替换，到了我在加个配置选项的时候🤔
> > 
> > 
> > 好的，希望可以手动配置需要转换的属性，这样对于不同的组件也能灵活处理，例如`['width', 'height', 'size']`😁
> 
> 这个vue模版编译后组件prop接收到的是转换后的，但是react，模版是处理成功了，但是编译后组件props接收到的还是原来没转换的🤔

allReplace:true是正常的，自定义配置有个bug
![image](https://github.com/user-attachments/assets/ef325bd8-e8d7-4804-8ac6-6ae2451853f3)
svg-icon
