### ISSUE TITLE
attributeList自定义配置bug

### ISSUE THREAD

**Issue by paker777** [cq112233/vite-plugin-style-to-vw#4]
allReplace:true是正常的，自定义配置有个bug
![image](https://github.com/user-attachments/assets/ef325bd8-e8d7-4804-8ac6-6ae2451853f3)

svg-icon组件代码
![image](https://github.com/user-attachments/assets/3580fec0-2843-42c5-9178-a326684ae4dc)

**Comment by cq112233** [comment]
> allReplace:true是正常的，自定义配置有个bug ![image](https://private-user-images.githubusercontent.com/85239013/352720350-ef325bd8-e8d7-4804-8ac6-6ae2451853f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwODQ5NzEsIm5iZiI6MTcyMjA4NDY3MSwicGF0aCI6Ii84NTIzOTAxMy8zNTI3MjAzNTAtZWYzMjViZDgtZThkNy00ODA0LThhYzYtNmFlMjQ1MTg1M2YzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDEyNTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZmJlNTAzZGNiMjQ1ZTY5MGU4ZmMwZGI5ZjQwYjkxNGFmNWM2MTg4MTE5ZmMzYTJiOGUwMzY1NjA4YWNiNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._KyKC3uj7uvILy8HONZcOfyfg30pbHUwGIWmF18X-QA)
> 
> svg-icon组件代码 ![image](https://private-user-images.githubusercontent.com/85239013/352720582-3580fec0-2843-42c5-9178-a326684ae4dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwODQ5NzEsIm5iZiI6MTcyMjA4NDY3MSwicGF0aCI6Ii84NTIzOTAxMy8zNTI3MjA1ODItMzU4MGZlYzAtMjg0My00MmM1LTkxNzgtYTMyNjY4NGFlNGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDEyNTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYmM0NDcyYzVmNTRlOTM5MWE4ZWMyYmJkZDZkNTI1ZjAyY2IyOGMwZWE4YTI2MDNlMmViYzQ1NjUwZTFlMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XYsnxHethaWPcV65bF2omFTouLhy13aecKm1LFLO_eI)

修复了👌

**Comment by paker777** [comment]
> > allReplace:true是正常的，自定义配置有个bug![图像](https://private-user-images.githubusercontent.com/85239013/352720350-ef325bd8-e8d7-4804-8ac6-6ae2451853f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwODQ5NzEsIm5iZiI6MTcyMjA4NDY3MSwicGF0aCI6Ii84NTIzOTAxMy8zNTI3MjAzNTAtZWYzMjViZDgtZThkNy00ODA0LThhYzYtNmFlMjQ1MTg1M2YzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDEyNTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZmJlNTAzZGNiMjQ1ZTY5MGU4ZmMwZGI5ZjQwYjkxNGFmNWM2MTg4MTE5ZmMzYTJiOGUwMzY1NjA4YWNiNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._KyKC3uj7uvILy8HONZcOfyfg30pbHUwGIWmF18X-QA)
> > svg-icon组件代码![图像](https://private-user-images.githubusercontent.com/85239013/352720582-3580fec0-2843-42c5-9178-a326684ae4dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwODQ5NzEsIm5iZiI6MTcyMjA4NDY3MSwicGF0aCI6Ii84NTIzOTAxMy8zNTI3MjA1ODItMzU4MGZlYzAtMjg0My00MmM1LTkxNzgtYTMyNjY4NGFlNGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDEyNTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYmM0NDcyYzVmNTRlOTM5MWE4ZWMyYmJkZDZkNTI1ZjAyY2IyOGMwZWE4YTI2MDNlMmViYzQ1NjUwZTFlMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XYsnxHethaWPcV65bF2omFTouLhy13aecKm1LFLO_eI)
> 
> 修复了👌

👍👍👍
